# Generated by Django 6.0.3 on 2026-03-27 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0002_alter_bin_location_description'),
        ('circuits', '0002_alter_circuit_name'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routeplan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled (Auto 4AM)'), ('manual', 'Manual (Admin Triggered)'), ('threshold', 'Threshold (Emergency - Bin Critical)')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('total_bins_in_circuit', models.PositiveIntegerField(default=0)),
                ('total_bins_selected', models.PositiveIntegerField(default=0)),
                ('fill_threshold_used', models.PositiveSmallIntegerField(default=70, help_text='Minimum fill % for bin to be included in route')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('scheduled_for', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='circuits.circuit')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null if auto-generated by Celery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_routes', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_plan', to='drivers.trip')),
            ],
            options={
                'verbose_name': 'Route Plan',
                'verbose_name_plural': 'Route Plans',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlanStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('fill_level_at_generation', models.PositiveSmallIntegerField()),
                ('battery_level_at_generation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance_from_previous_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='bins.bin')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.routeplan')),
            ],
            options={
                'verbose_name': 'Route Plan Stop',
                'verbose_name_plural': 'Route Plan Stops',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['circuit', '-scheduled_for'], name='routing_rou_circuit_ee90eb_idx'),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['status', '-scheduled_for'], name='routing_rou_status_595a83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routeplanstop',
            unique_together={('route_plan', 'bin')},
        ),
    ]
