# Generated by Django 6.0.3 on 2026-03-27 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0002_alter_bin_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('household', 'Household'), ('business', 'Business'), ('government', 'Government')], default='household', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Full monthly fee in GHS', max_digits=10)),
                ('bin_contribution', models.DecimalField(decimal_places=2, help_text='Monthly bin cost contribution in GHS', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month billing is due')),
                ('next_billing_date', models.DateField()),
                ('started_at', models.DateField()),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='bins.bin')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('subscription', 'Monthly Subscription'), ('bin_contribution', 'Bin Contribution'), ('penalty', 'Penalty Fee')], max_length=20)),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo_money', 'AirtelTigo Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('momo_number', models.CharField(blank=True, max_length=20)),
                ('momo_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('momo_network', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['subscription', '-initiated_at'], name='billing_pay_subscri_494e8b_idx'), models.Index(fields=['status', '-initiated_at'], name='billing_pay_status_6fc4c5_idx')],
            },
        ),
    ]
