# Generated by Django 6.0.3 on 2026-03-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
