import uuid
from django.db import models


class Routeplan(models.Model):

    class Status(models.TextChoices):
        GENERATING = 'generating', 'Generating'
        READY = 'ready', 'Ready'
        DISPATCHED = 'dispatched', 'Dispatched'
        COMPLETED = 'completed', 'Completed'
        FAILED = 'failed', 'Failed'

    class TriggerType(models.TextChoices):
        SCHEDULED = 'scheduled', 'Scheduled (Auto 4AM)'
        MANUAL = 'manual', 'Manual (Admin Triggered)'
        THRESHOLD = 'threshold', 'Threshold (Emergency - Bin Critical)'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    circuit = models.ForeignKey(
        'circuits.Circuit',
        on_delete=models.CASCADE,
        related_name='route_plans'
    )
    trip = models.OneToOneField(
        'drivers.Trip',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='route_plan'
    )

    # How and when this route was triggered
    trigger_type = models.CharField(max_length=20, choices=TriggerType.choices, default=TriggerType.SCHEDULED)
    triggered_by = models.ForeignKey(
        'auth.User',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='triggered_routes',
        help_text="Null if auto-generated by Celery"
    )

    # Status
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.GENERATING)
    failure_reason = models.TextField(blank=True)

    # Route metrics
    total_bins_in_circuit = models.PositiveIntegerField(default=0)
    total_bins_selected = models.PositiveIntegerField(default=0)
    fill_threshold_used = models.PositiveSmallIntegerField(
        default=70,
        help_text="Minimum fill % for bin to be included in route"
    )
    estimated_duration_minutes = models.PositiveIntegerField(null=True, blank=True)
    estimated_distance_km = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)

    # Timestamps
    scheduled_for = models.DateField()
    generated_at = models.DateTimeField(null=True, blank=True)
    dispatched_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-scheduled_for', '-created_at']
        verbose_name = 'Route Plan'
        verbose_name_plural = 'Route Plans'
        indexes = [
            models.Index(fields=['circuit', '-scheduled_for']),
            models.Index(fields=['status', '-scheduled_for']),
        ]

    def __str__(self):
        return f"Route {self.circuit.code} - {self.scheduled_for} - {self.status}"

    @property
    def selection_rate(self):
        if self.total_bins_in_circuit == 0:
            return 0
        return round((self.total_bins_selected / self.total_bins_in_circuit) * 100, 1)


class RoutePlanStop(models.Model):
    """
    Each bin stop in a generated route plan.
    Ordered by the routing algorithm.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    route_plan = models.ForeignKey(
        Routeplan,
        on_delete=models.CASCADE,
        related_name='stops'
    )
    bin = models.ForeignKey(
        'bins.Bin',
        on_delete=models.CASCADE,
        related_name='route_stops'
    )

    # Position in the optimized route
    order = models.PositiveIntegerField()

    # Snapshot of bin state at time of route generation
    fill_level_at_generation = models.PositiveSmallIntegerField()
    battery_level_at_generation = models.PositiveSmallIntegerField(null=True, blank=True)

    # Distance from previous stop in km
    distance_from_previous_km = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    # Estimated arrival time at this stop
    estimated_arrival = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['order']
        verbose_name = 'Route Plan Stop'
        verbose_name_plural = 'Route Plan Stops'
        unique_together = ['route_plan', 'bin']

    def __str__(self):
        return f"Stop {self.order} - {self.bin.serial_number} - {self.fill_level_at_generation}%"