# Generated by Django 6.0.3 on 2026-03-27 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_eui', models.CharField(help_text='LoRaWAN Device EUI', max_length=16, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('bin_type', models.CharField(choices=[('general', 'General Waste'), ('recyclable', 'Recyclable'), ('organic', 'Organic')], default='general', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_description', models.CharField(help_text='e.g. In front of Accra Mall gate', max_length=255)),
                ('capacity_litres', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged')], default='active', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='circuits.circuit')),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fill_level', models.PositiveSmallIntegerField(help_text='Fill percentage 0-100')),
                ('battery_level', models.PositiveSmallIntegerField(help_text='Battery percentage 0-100')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_tampered', models.BooleanField(default=False)),
                ('signal_strength', models.IntegerField(blank=True, help_text='RSSI in dBm', null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='bins.bin')),
            ],
            options={
                'verbose_name': 'Bin Telemetry',
                'verbose_name_plural': 'Bin Telemetry Records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bin', '-recorded_at'], name='bins_bintel_bin_id_47eaa8_idx')],
            },
        ),
    ]
