# Generated by Django 6.0.3 on 2026-03-27 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('bins', '0002_alter_bin_location_description'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('bin_tampered', 'Bin Tampered'), ('bin_offline', 'Bin Offline'), ('bin_low_battery', 'Bin Low Battery'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('trip_overdue', 'Trip Overdue'), ('payment_due', 'Payment Due'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('driver_anomaly', 'Driver Location Anomaly'), ('system_alert', 'System Alert')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], default='in_app', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bins.bin')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='billing.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='drivers.trip')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'), models.Index(fields=['priority', 'is_sent'], name='notificatio_priorit_d3a0c0_idx')],
            },
        ),
    ]
